// Les textes de la surface (#16 ; fiche, § 11). Ils seront révisés d'après la bible narrative (#43, #60).
// Ton : celui d'un logiciel bien fait. Des phrases courtes et polies, sans point d'exclamation ni
// humour appuyé : « Objectif atteint. » plutôt que « Bravo ! ». On ne sait pas ce que l'exploitation
// produit, seulement ce qu'elle rapporte. Aucun texte ne mentionne « creuser », et l'aide ne dit rien
// du bandeau.
export const textes: Record<string, string> = {
  // ——— Le tableau de bord
  titre: "Tableau de bord",
  credits: "Crédits",
  production: "Production",
  objectif: "Objectif",
  "objectif.atteint": "Objectif atteint.",
  "objectifs.fini": "Tous les objectifs sont atteints.",
  "objectifs.atteints": "Objectifs atteints",
  "objectifs.aucun": "Aucun objectif atteint pour l'instant.",
  // La valeur convertible, nommée à l'écran de fouille (docs/strates/descente-1-2.md, P3).
  "fouille.valeur": "Crédits gagnés",
  graphique: "Production en cr/s, 15 dernières minutes",
  "graphique.debut": "il y a 15 min",
  "graphique.fin": "maintenant",
  produire: "Produire",
  clic: "+{valeur} par clic",
  generateurs: "Moyens de production",
  "en-service": "{n} en service",
  "acheter.1": "Acheter",
  "acheter.10": "×10",
  "acheter.10.nom": "Acheter 10",
  "acheter.max": "Max",
  "acheter.max.nom": "Acheter autant que possible",
  ameliorations: "Améliorations",
  "ameliorations.aucune": "Aucune amélioration disponible pour l'instant.",

  // ——— Les objectifs (fiche, § 3) : chacun désigne la prochaine chose à faire
  "objectif.1": "Produire 15 cr",
  "objectif.2": "Acheter un poste",
  "objectif.3": "Atteindre 1 cr/s",
  "objectif.4": "Acheter une amélioration",
  "objectif.5": "Atteindre 10 cr/s",
  "objectif.6": "Atteindre 100 cr/s",
  "objectif.7": "Atteindre 1 k cr/s",
  "objectif.8": "Atteindre 10 k cr/s",
  "objectif.9": "Atteindre 100 k cr/s",
  "objectif.10": "Atteindre 1 M cr/s",

  // ——— Les moyens de production, et leur infobulle
  "generateur.poste": "Poste",
  "generateur.poste.description": "Un poste de travail, occupé à plein temps.",
  "generateur.equipe": "Équipe",
  "generateur.equipe.description": "Plusieurs postes, un responsable, des objectifs communs.",
  "generateur.serveur": "Serveur",
  "generateur.serveur.description": "Il traite ce qu'on lui confie, jour et nuit.",
  "generateur.chaine": "Chaîne",
  "generateur.chaine.description": "Chaque étape alimente la suivante.",
  "generateur.turbine": "Turbine",
  "generateur.turbine.description": "Elle fournit l'énergie de toute l'exploitation.",
  "generateur.usine": "Usine",
  "generateur.usine.description": "Un site complet, avec ses équipes et ses machines.",
  "generateur.filiale": "Filiale",
  "generateur.filiale.description": "Une société à part entière, qui rapporte à la maison mère.",

  "effet.generateur": "{nom} : production ×{facteur}",
  "effet.global": "Toute la production ×{facteur}",
  "effet.clic": "Produire ×{facteur}",
  "effet.partClic": "Produire : +{part} % de la production",

  // ——— Les améliorations, et leur infobulle
  "amelioration.poste-10": "Double écran",
  "amelioration.poste-10.description": "Deux fois plus de fenêtres ouvertes.",
  "amelioration.poste-25": "Raccourcis clavier",
  "amelioration.poste-25.description": "Les gestes les plus fréquents, en une touche.",
  "amelioration.poste-50": "Poste ergonomique",
  "amelioration.poste-50.description": "Moins de fatigue, moins de pauses.",
  "amelioration.equipe-10": "Réunion hebdomadaire",
  "amelioration.equipe-10.description": "Une heure par semaine, pour que chacun sache quoi faire.",
  "amelioration.equipe-25": "Outil partagé",
  "amelioration.equipe-25.description": "Tout le monde travaille sur le même document.",
  "amelioration.equipe-50": "Rituels d'équipe",
  "amelioration.equipe-50.description": "Les habitudes qui font gagner du temps.",
  "amelioration.serveur-10": "Mise en cache",
  "amelioration.serveur-10.description": "Ce qui a déjà été calculé ne l'est pas deux fois.",
  "amelioration.serveur-25": "Redondance",
  "amelioration.serveur-25.description": "Quand un serveur s'arrête, un autre prend le relais.",
  "amelioration.serveur-50": "Virtualisation",
  "amelioration.serveur-50.description": "Dix serveurs dans une seule machine.",
  "amelioration.chaine-10": "Cadence",
  "amelioration.chaine-10.description": "La chaîne tourne plus vite, sans à-coups.",
  "amelioration.chaine-25": "Flux tendu",
  "amelioration.chaine-25.description": "Chaque pièce arrive au moment où elle sert.",
  "amelioration.chaine-50": "Robotisation",
  "amelioration.chaine-50.description": "Les gestes répétitifs sont confiés aux machines.",
  "amelioration.turbine-10": "Maintenance préventive",
  "amelioration.turbine-10.description": "On répare avant que ça casse.",
  "amelioration.turbine-25": "Pales optimisées",
  "amelioration.turbine-25.description": "Le même flux, plus d'énergie.",
  "amelioration.turbine-50": "Haut rendement",
  "amelioration.turbine-50.description": "Presque rien ne se perd.",
  "amelioration.usine-10": "Trois-huit",
  "amelioration.usine-10.description": "L'usine ne s'arrête plus.",
  "amelioration.usine-25": "Amélioration continue",
  "amelioration.usine-25.description": "Chaque semaine, un peu mieux que la précédente.",
  "amelioration.usine-50": "Usine connectée",
  "amelioration.usine-50.description": "Chaque machine rend compte de ce qu'elle fait.",
  "amelioration.filiale-10": "Synergies",
  "amelioration.filiale-10.description": "Les filiales partagent leurs clients.",
  "amelioration.filiale-25": "Mutualisation",
  "amelioration.filiale-25.description": "Un seul service pour toutes les filiales.",
  "amelioration.filiale-50": "Holding",
  "amelioration.filiale-50.description": "Une société qui détient les autres.",
  "amelioration.globale-1": "Process",
  "amelioration.globale-1.description": "Chaque tâche a désormais sa procédure écrite.",
  "amelioration.globale-2": "Réorganisation",
  "amelioration.globale-2.description": "Un nouvel organigramme, les mêmes personnes.",
  "amelioration.globale-3": "Plan stratégique",
  "amelioration.globale-3.description": "Cinq ans d'objectifs, dans un seul document.",
  "amelioration.clic-1": "Souris ergonomique",
  "amelioration.clic-1.description": "Le clic tombe mieux sous la main.",
  "amelioration.clic-2": "Double clic",
  "amelioration.clic-2.description": "Deux fois plus d'effet pour le même geste.",
  "amelioration.clic-3": "Macro",
  "amelioration.clic-3.description": "Une suite de clics, enregistrée une fois pour toutes.",
  "amelioration.clic-4": "Suivi individuel",
  "amelioration.clic-4.description": "Chacun voit ce que son travail rapporte.",
  "amelioration.clic-5": "Objectifs individuels",
  "amelioration.clic-5.description": "Chacun a désormais ses propres chiffres.",

  // ——— L'aide : une page courte, qui décrit tout le tableau de bord et rien d'autre
  aide: "Aide",
  "aide.titre": "Aide du tableau de bord",
  "aide.fermer": "Fermer",
  "aide.credits.titre": "Crédits",
  "aide.credits":
    "Les crédits sont la ressource de l'exploitation. Vous en gagnez en produisant, et vous les dépensez en achats.",
  "aide.produire.titre": "Produire",
  "aide.produire":
    "Chaque clic sur « Produire » rapporte des crédits. Le montant est indiqué sous le bouton.",
  "aide.generateurs.titre": "Moyens de production",
  "aide.generateurs":
    "Chaque moyen de production rapporte des crédits à chaque seconde, sans intervention. Son prix augmente de 15 % à chaque achat. « ×10 » en achète dix d'un coup, et « Max » autant que vos crédits le permettent. Un nouveau moyen apparaît quand vos gains approchent de son prix.",
  "aide.ameliorations.titre": "Améliorations",
  "aide.ameliorations":
    "Une amélioration s'achète une seule fois. Elle double la production d'un moyen, augmente toute la production, ou améliore « Produire ». Les améliorations d'un moyen apparaissent quand vous en avez 10, 25 puis 50 en service.",
  "aide.production.titre": "Production",
  "aide.production":
    "La production totale, en crédits par seconde. Le graphique montre son évolution sur les 15 dernières minutes.",
  "aide.objectifs.titre": "Objectifs",
  "aide.objectifs":
    "L'objectif courant indique la prochaine étape, et sa barre, le chemin qui reste. Les objectifs atteints restent dans la liste.",
  "aide.absence.titre": "Absence",
  "aide.absence":
    "Quand vous fermez le tableau de bord, la production continue, à 80 %, pendant 12 heures au plus.",
  "aide.notation.titre": "Notation",
  "aide.notation": "cr : crédit. k : mille. M : million. Md : milliard.",

  // ——— Les traces laissées au fond (strate 8, #109) : trois lignes au plus
  "trace.1": "Objectif 10 : atteindre 1 M cr/s. Atteint.",
  "trace.2": "Tous les objectifs sont atteints.",
  "trace.3": "La production continue.",
};
