// Textes provisoires de la surface : ils seront réécrits par #16, d'après la bible narrative.
// Ton : celui d'un logiciel bien fait. Aucun texte ne mentionne « creuser » (fiche, § 11).
export const textes: Record<string, string> = {
  titre: "Tableau de bord",
  credits: "Crédits",
  production: "Production",
  objectif: "Objectif",
  "objectifs.fini": "Tous les objectifs sont atteints.",
  "objectif.1": "Produire 15 cr",
  "objectif.2": "Acheter un poste",
  "objectif.3": "Atteindre 1 cr/s",
  "objectif.4": "Acheter une amélioration",
  "objectif.5": "Atteindre 10 cr/s",
  "objectif.6": "Atteindre 100 cr/s",
  "objectif.7": "Atteindre 1 k cr/s",
  "objectif.8": "Atteindre 10 k cr/s",
  "objectif.9": "Atteindre 100 k cr/s",
  "objectif.10": "Atteindre 1 M cr/s",
  graphique: "Production, 15 dernières minutes",
  produire: "Produire",
  generateurs: "Moyens de production",
  possedes: "Possédés",
  "acheter.1": "Acheter",
  "acheter.10": "×10",
  "acheter.max": "Max",
  ameliorations: "Améliorations",
  "ameliorations.aucune": "Aucune amélioration disponible pour l'instant.",

  "generateur.poste": "Poste",
  "generateur.equipe": "Équipe",
  "generateur.serveur": "Serveur",
  "generateur.chaine": "Chaîne",
  "generateur.turbine": "Turbine",
  "generateur.usine": "Usine",
  "generateur.filiale": "Filiale",

  "effet.generateur": "{nom} : production ×{facteur}",
  "effet.global": "Toute la production ×{facteur}",
  "effet.clic": "Produire ×{facteur}",
  "effet.partClic": "Produire : +{part} % de la production",

  "amelioration.poste-10": "Double écran",
  "amelioration.poste-25": "Raccourcis clavier",
  "amelioration.poste-50": "Poste ergonomique",
  "amelioration.equipe-10": "Réunion hebdomadaire",
  "amelioration.equipe-25": "Outil partagé",
  "amelioration.equipe-50": "Rituels d'équipe",
  "amelioration.serveur-10": "Mise en cache",
  "amelioration.serveur-25": "Redondance",
  "amelioration.serveur-50": "Virtualisation",
  "amelioration.chaine-10": "Cadence",
  "amelioration.chaine-25": "Flux tendu",
  "amelioration.chaine-50": "Robotisation",
  "amelioration.turbine-10": "Maintenance préventive",
  "amelioration.turbine-25": "Pales optimisées",
  "amelioration.turbine-50": "Haut rendement",
  "amelioration.usine-10": "Trois-huit",
  "amelioration.usine-25": "Amélioration continue",
  "amelioration.usine-50": "Usine connectée",
  "amelioration.filiale-10": "Synergies",
  "amelioration.filiale-25": "Mutualisation",
  "amelioration.filiale-50": "Holding",
  "amelioration.globale-1": "Process",
  "amelioration.globale-2": "Réorganisation",
  "amelioration.globale-3": "Plan stratégique",
  "amelioration.clic-1": "Souris ergonomique",
  "amelioration.clic-2": "Double clic",
  "amelioration.clic-3": "Macro",
  "amelioration.clic-4": "Suivi individuel",
  "amelioration.clic-5": "Objectifs individuels",
};
